# Datei: k8s/amazon/auth-worker-nodes.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::397921036163:role/mwa-worker-nodes-NodeInstanceRole-1SI1D5PP5YMHD
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

