# Datei: k8s/amazon/auth-worker-nodes.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::524904216919:role/mwa-worker-nodes-NodeInstanceRole-6FZW5G7DVLJM
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

