# Datei: grafana/provisioning/datasources/influx.yml
apiVersion: 1
datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influx:8086
  database: telegraf
  isDefault: true
  version: 1
  jsonData:
    timeInterval: ">10s"
  editable: true

