services:
  grafana:
    image: docbuc/grafana:4
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=geheim
  telegraf:
    image: docbuc/telegraf:4
    restart: always
    environment:
      - INFLUXDB_TOKEN=gahPae6deivo0aenooy7thoheewaex9eeNgaePah8dee5io6neewooSe3bemu9gi
      - INFLUXDB_ORG=dockerbuch
      - INFLUXDB_BUCKET=dockerbuch
  influx:
    image: influxdb:2.7
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dockerbuch
      - DOCKER_INFLUXDB_INIT_PASSWORD=geheimgeheim
      - DOCKER_INFLUXDB_INIT_ORG=dockerbuch
      - DOCKER_INFLUXDB_INIT_BUCKET=dockerbuch
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=gahPae6deivo0aenooy7thoheewaex9eeNgaePah8dee5io6neewooSe3bemu9gi
