apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: influx
  name: influx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influx
    spec:
      containers:
      - env:
        - name: INFLUXDB_DB
          value: telegraf
        - name: INFLUXDB_USER
          value: telegraf
        - name: INFLUXDB_USER_PASSWORD
          value: iijineeZ9iet
        image: influxdb
        name: influx
        ports:
        - containerPort: 8086
        resources: {}
      restartPolicy: Always
status: {}
