apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: influx
  name: influx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/grafana-default: "true"
        io.kompose.service: influx
    spec:
      containers:
        - env:
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: gahPae6deivo0aenooy7thoheewaex9eeNgaePah8dee5io6neewooSe3bemu9gi
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: dockerbuch
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: dockerbuch
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: geheimgeheim
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: dockerbuch
          image: influxdb:2.7
          name: influx
          ports:
            - containerPort: 8086
              hostPort: 8086
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
