apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: telegraf
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: telegraf
    spec:
      containers:
      - image: docbuc/telegraf:2
        name: telegraf
        resources: {}
      restartPolicy: Always
status: {}
