# Datei: k8s/google/cert.yaml
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dockerbuch-diary-cert
  namespace: default
spec:
  secretName: dockerbuch-diary-cert
  issuerRef:
    name: letsencrypt-prod
  commonName: k8s-diary.dockerbuch.info
  dnsNames:
  - k8s-diary.dockerbuch.info
  acme:
    config:
    - http01:
        ingress: frontend-ingress
      domains:
      - k8s-diary.dockerbuch.info
